name       : boto3
version    : 1.4.4
release    : 3
source     :
    - https://github.com/boto/boto3/archive/1.4.4.tar.gz : c760ca47a34fb54e44b90fc28d87a50353df527b39e815f399c481bab7d351c6
license    : Apache-2.0
component  : programming.python
summary    : AWS SDK for Python
description: |
    AWS SDK for Python
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
